name: grocery_application
description: "A Grocery Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  dio: ^5.4.2+1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.4.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.2


dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.2
  mocktail: ^1.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
